# Generated by Django 6.1 on 2026-09-02 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_name', models.CharField(max_length=255)),
                ('ecgains', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('bid_url', models.URLField(max_length=1000)),
                ('comments', models.TextField(blank=True)),
                ('module_name', models.CharField(blank=True, max_length=255)),
                ('bid_type', models.CharField(choices=[('New', 'New'), ('Update/Repair', 'Update Repair')], max_length=20)),
                ('priority', models.CharField(choices=[('High', 'High'), ('Normal', 'Normal')], default='Normal', max_length=20)),
                ('has_bid', models.BooleanField(default=False)),
                ('procurement_type', models.CharField(choices=[('Procurement Spider', 'Procurement Spider'), ('Bonfire Spider', 'Bonfire Spider'), ('Bidnet AMR', 'Bidnet Amr'), ('Demandstar AMR', 'Demandstar Amr')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bids', to='bids.developer')),
            ],
        ),
    ]
