# Generated by Django 6.1 on 2026-09-02 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='has_bid',
            new_name='has_bids',
        ),
    ]
