# Generated by Django 6.1 on 2026-09-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_rename_has_bid_bid_has_bids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='ecgains',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
