# Generated by Django 5.0.14 on 2026-09-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_alter_bid_ecgains'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_bid_id', models.PositiveBigIntegerField()),
                ('agency_name', models.CharField(max_length=255)),
                ('ecgains', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=100)),
                ('initials', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('bid_url', models.URLField(max_length=1000)),
                ('comments', models.TextField(blank=True)),
                ('module_name', models.CharField(blank=True, max_length=255)),
                ('developer_name', models.CharField(max_length=100)),
                ('bid_type', models.CharField(max_length=20)),
                ('priority', models.CharField(max_length=20)),
                ('has_bids', models.BooleanField(default=False)),
                ('procurement_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'archive',
                'ordering': ('-deleted_at', '-id'),
            },
        ),
    ]
