# Generated by Django 5.0.14 on 2026-09-03 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_archivedbid_alter_bid_id_alter_developer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_type',
            field=models.CharField(choices=[('New', 'New'), ('Update/Repair', 'Update Repair')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='bid',
            name='procurement_type',
            field=models.CharField(choices=[('Procurement Spider', 'Procurement Spider'), ('Bonfire Spider', 'Bonfire Spider'), ('Bidnet AMR', 'Bidnet Amr'), ('Demandstar AMR', 'Demandstar Amr')], default='Procurement Spider', max_length=50),
        ),
    ]
