# Generated by Django 5.0.14 on 2026-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0005_alter_bid_bid_type_alter_bid_procurement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'agencies',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='bid',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Normal', 'Normal'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
    ]
